# Generated by Django 3.1.7 on 2021-05-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0002_auto_20210523_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfstudywordname',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
