# Generated by Django 3.1.7 on 2021-05-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0003_auto_20210523_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfstudywordname',
            options={},
        ),
        migrations.CreateModel(
            name='ModelUrlText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('text', models.TextField()),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_url_text', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
