# Generated by Django 3.1.7 on 2021-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0004_auto_20210524_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelurltext',
            name='text',
            field=models.TextField(default=True, null=True),
        ),
    ]
