# Generated by Django 3.1.7 on 2021-05-24 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0006_auto_20210524_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelurltext',
            name='date_url_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 20, 59, 24, 583939)),
        ),
    ]
