# Generated by Django 3.1.7 on 2021-05-24 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0007_modelurltext_date_url_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelurltext',
            name='date_url_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 21, 0, 21, 535049)),
        ),
    ]
