# Generated by Django 3.1.7 on 2021-05-25 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0008_auto_20210524_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count_cost_lessons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelurltext',
            name='date_url_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 53, 18, 371743)),
        ),
    ]
