# Generated by Django 3.1.7 on 2021-05-27 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_teacher', '0009_auto_20210525_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelurltext',
            options={'verbose_name': 'Ссылка на занятие', 'verbose_name_plural': 'Ссылки на занятия'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Ваша фамилия'),
        ),
        migrations.AlterField(
            model_name='modelurltext',
            name='date_url_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 21, 34, 18, 282365)),
        ),
        migrations.AlterField(
            model_name='studywords',
            name='english_word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studywords',
            name='rus_word',
            field=models.TextField(max_length=50),
        ),
    ]
